// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apka.Models;

#nullable disable

namespace apka.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250614230700_InitialCreationNewDb")]
    partial class InitialCreationNewDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apka.Models.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAutor");

                    b.ToTable("Autorzy");
                });

            modelBuilder.Entity("apka.Models.Kategoria", b =>
                {
                    b.Property<int>("IdKategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategoria"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKategoria");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("apka.Models.Poziom", b =>
                {
                    b.Property<int>("IdPoziom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPoziom"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPoziom");

                    b.ToTable("Poziomy");
                });

            modelBuilder.Entity("apka.Models.Produkt", b =>
                {
                    b.Property<int>("IdProdukt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProdukt"));

                    b.Property<int>("IdAutor")
                        .HasColumnType("int");

                    b.Property<int>("IdKategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdPoziom")
                        .HasColumnType("int");

                    b.Property<int>("IdSkladnik")
                        .HasColumnType("int");

                    b.Property<string>("Instrukcje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProdukt");

                    b.HasIndex("IdAutor");

                    b.HasIndex("IdKategoria");

                    b.HasIndex("IdPoziom");

                    b.HasIndex("IdSkladnik");

                    b.ToTable("Produkty");
                });

            modelBuilder.Entity("apka.Models.Skladnik", b =>
                {
                    b.Property<int>("IdSkladnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSkladnik"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSkladnik");

                    b.ToTable("Skladnik");
                });

            modelBuilder.Entity("apka.Models.Produkt", b =>
                {
                    b.HasOne("apka.Models.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apka.Models.Kategoria", "Kategoria")
                        .WithMany()
                        .HasForeignKey("IdKategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apka.Models.Poziom", "Poziom")
                        .WithMany()
                        .HasForeignKey("IdPoziom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apka.Models.Skladnik", "Skladnik")
                        .WithMany()
                        .HasForeignKey("IdSkladnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Kategoria");

                    b.Navigation("Poziom");

                    b.Navigation("Skladnik");
                });
#pragma warning restore 612, 618
        }
    }
}
